@startuml
component Fachbausteine as fachbaustein {
    component "Bestellungs-Modul" as bestellung
    component "Antragsteller-Modul" as antragsteller
    component "Fahrzeug-Modul" as fahrzeug
}

bestellung --> antragsteller
bestellung --> fahrzeug
@enduml