<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>antragsteller</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>antragsteller-usecase</artifactId>
    <packaging>pom</packaging>
    <name>antragsteller-usecase</name>
    <description>Usecase-Ring für die Fachlichkeit Antragsteller</description>

    <modules>
        <module>in</module>
        <module>out</module>
        <module>exception</module>
    </modules>
</project>