<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>antragsteller-usecase</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>antragsteller-usecase-in</artifactId>
    <name>antragsteller-usecase-in</name>
    <description>Input Usecases für die Fachlichkeit Antragsteller</description>

    <dependencies>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain-model</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-exception</artifactId>
        </dependency>
    </dependencies>
</project>