<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>business-logic-modulith</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>architecture-test</artifactId>
    <name>architecture-test</name>
    <dependencies>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>${archunit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-model</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-service</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-prozessmodell</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase-exception</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-adapter-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-adapter-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain-model</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain-service</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-exception</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-adapter-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-adapter-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-domain-model</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-domain-service</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase-exception</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-adapter-in</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-adapter-out</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven-surefire-plugin.version}</version>
            </plugin>
        </plugins>
    </build>
</project>