<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.4</version>
        <relativePath/>
    </parent>

    <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
    <artifactId>business-logic-modulith</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>business-logic-modulith</name>
    <description>Abbildung der Fachlichkeit</description>

    <modules>
        <module>bestellung</module>
        <module>antragsteller</module>
        <module>fahrzeug</module>
        <module>app</module>
        <module>aufgabenliste</module>

        <module>technical</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <h2.version>2.3.232</h2.version>
        <camunda7.base.version>7.23.0</camunda7.base.version>
        <slf4j.version>2.0.17</slf4j.version>
        <lombok.version>1.18.38</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <domainprimitives-java.version>0.1.1</domainprimitives-java.version>
        <gson.version>2.13.2</gson.version>
        <gson-fire.version>1.9.0</gson-fire.version>
        <threetenbp.version>1.7.2</threetenbp.version>
        <okio.version>3.16.0</okio.version>
        <okhttp.version>5.1.0</okhttp.version>
        <jakarta.annotation-api.version>3.0.0</jakarta.annotation-api.version>
        <swagger-annotations.version>1.6.2</swagger-annotations.version>
        <logging-interceptor.version>5.1.0</logging-interceptor.version>
        <jackson-databind-nullable.version>0.2.7</jackson-databind-nullable.version>

        <camunda-process-test-coverage.version>2.8.1</camunda-process-test-coverage.version>
        <junit.version>5.13.4</junit.version>
        <assertj.version>3.27.3</assertj.version>
        <wiremock-standalone.version>3.13.1</wiremock-standalone.version>
        <mockito.version>5.18.0</mockito.version>
        <logback-classic.version>1.5.18</logback-classic.version>
        <wiremock-standalone.version>3.13.1</wiremock-standalone.version>
        <archunit.version>1.4.1</archunit.version>

        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-antrun-plugin.version>3.1.0</maven-antrun-plugin.version>
        <maven-surefire-plugin.version>3.4.0</maven-surefire-plugin.version>
        <openapi-generator-maven-plugin.version>7.15.0</openapi-generator-maven-plugin.version>
        <jacoco-maven-plugin.version>0.8.13</jacoco-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-prozessmodell</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-adapter</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-domain</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-usecase</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-adapter</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>antragsteller-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-adapter</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-domain</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-usecase</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-adapter</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>artifact-deployment-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>testcoverage</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-domain</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-usecase</artifactId>
                <type>pom</type>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-adapter</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>aufgabenliste-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>camunda-rest-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>uuid-generator</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>architecture-test</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.h2database</groupId>
                <artifactId>h2</artifactId>
                <version>${h2.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.domain-primitives</groupId>
                <artifactId>domainprimitives-java</artifactId>
                <version>${domainprimitives-java.version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
            <dependency>
                <groupId>io.gsonfire</groupId>
                <artifactId>gson-fire</artifactId>
                <version>${gson-fire.version}</version>
            </dependency>
            <dependency>
                <groupId>org.threeten</groupId>
                <artifactId>threetenbp</artifactId>
                <version>${threetenbp.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okio</groupId>
                <artifactId>okio</artifactId>
                <version>${okio.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>${okhttp.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.annotation</groupId>
                <artifactId>jakarta.annotation-api</artifactId>
                <version>${jakarta.annotation-api.version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>${swagger-annotations.version}</version>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>logging-interceptor</artifactId>
                <version>${logging-interceptor.version}</version>
            </dependency>
            <dependency>
                <groupId>org.openapitools</groupId>
                <artifactId>jackson-databind-nullable</artifactId>
                <version>${jackson-databind-nullable.version}</version>
            </dependency>

            <dependency>
                <groupId>org.camunda.bpm.springboot</groupId>
                <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
                <version>${camunda7.version}</version>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm.springboot</groupId>
                <artifactId>camunda-bpm-spring-boot-starter-external-task-client</artifactId>
                <version>${camunda7.version}</version>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm</groupId>
                <artifactId>camunda-bpm-junit5</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm</groupId>
                <artifactId>camunda-bpm-assert</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.community.mockito</groupId>
                <artifactId>camunda-platform-7-mockito</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.community.process_test_coverage</groupId>
                <artifactId>camunda-process-test-coverage-junit5-platform-7</artifactId>
                <version>${camunda-process-test-coverage.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.wiremock</groupId>
                <artifactId>wiremock-standalone</artifactId>
                <version>${wiremock-standalone.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>mockwebserver</artifactId>
                <version>${mockwebserver.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback-classic.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${jacoco-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>jacoco-check</id>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <rule>
                                    <element>PACKAGE</element>
                                    <limits>
                                        <limit>
                                            <counter>LINE</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.80</minimum>
                                        </limit>
                                        <!--TODO: Tests ergänzen, um Branch Coverage auf 80 % zu erhöhen-->
                                        <!--<limit>
                                            <counter>BRANCH</counter>
                                            <value>COVEREDRATIO</value>
                                            <minimum>0.80</minimum>
                                        </limit>-->
                                    </limits>
                                </rule>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>

        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.openapitools</groupId>
                    <artifactId>openapi-generator-maven-plugin</artifactId>
                    <version>${openapi-generator-maven-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>${maven-antrun-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>