<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.4</version>
        <relativePath/>
    </parent>

    <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
    <artifactId>business-logic-modulith</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>business-logic-modulith</name>
    <description>Abbildung der Fachlichkeit</description>

    <modules>
        <module>bestellung</module>
        <module>uuid-generator</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <camunda7.base.version>7.23.0</camunda7.base.version>
        <lombok.version>1.18.38</lombok.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <domainprimitives-java.version>0.1.1</domainprimitives-java.version>
        <camunda-process-test-coverage.version>2.8.1</camunda-process-test-coverage.version>
        <mockwebserver.version>4.12.0</mockwebserver.version>

        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-domain-prozessmodell</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>bestellung-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain-model</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain-service</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-domain-prozessmodell</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-out</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-usecase-exception</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-adapter-in</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>fahrzeug-adapter-out</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
                <artifactId>uuid-generator</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>io.github.domain-primitives</groupId>
                <artifactId>domainprimitives-java</artifactId>
                <version>${domainprimitives-java.version}</version>
            </dependency>

            <dependency>
                <groupId>org.camunda.bpm.springboot</groupId>
                <artifactId>camunda-bpm-spring-boot-starter-rest</artifactId>
                <version>${camunda7.version}</version>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm.springboot</groupId>
                <artifactId>camunda-bpm-spring-boot-starter-external-task-client</artifactId>
                <version>${camunda7.version}</version>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm</groupId>
                <artifactId>camunda-bpm-junit5</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.bpm</groupId>
                <artifactId>camunda-bpm-assert</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.community.mockito</groupId>
                <artifactId>camunda-platform-7-mockito</artifactId>
                <version>${camunda7.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.camunda.community.process_test_coverage</groupId>
                <artifactId>camunda-process-test-coverage-junit5-platform-7</artifactId>
                <version>${camunda-process-test-coverage.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>mockwebserver</artifactId>
                <version>${mockwebserver.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven-compiler-plugin.version}</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>