<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>business-logic-modulith</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>antragsteller</artifactId>
    <packaging>pom</packaging>
    <name>antragsteller</name>
    <description>Fachlichkeit Antragsteller</description>

    <modules>
        <module>adapter</module>
        <module>domain</module>
        <module>usecase</module>
    </modules>

</project>