<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>bestellung</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>bestellung-domain</artifactId>
    <packaging>pom</packaging>
    <name>bestellung-domain</name>
    <description>Domain-Ring für die Fachlichkeit Bestellung</description>

    <modules>
        <module>model</module>
        <module>prozessmodell</module>
        <module>service</module>
    </modules>
</project>