<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
        <artifactId>business-logic-modulith</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>app</artifactId>
    <name>app</name>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>${archunit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-adapter</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-adapter-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-adapter-in</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-service</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-model</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-domain-prozessmodell</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>bestellung-usecase-in</artifactId>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-adapter</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-adapter-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-adapter-in</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain-service</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-domain-model</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>antragsteller-usecase-in</artifactId>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-adapter</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-adapter-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-adapter-in</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-domain</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-domain-service</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-domain-model</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>fahrzeug-usecase-in</artifactId>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-adapter</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-adapter-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-adapter-in</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-domain</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-domain-service</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-usecase</artifactId>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-usecase-out</artifactId>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>artifact-deployment-usecase-in</artifactId>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>testcoverage</artifactId>
        </dependency>

        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste</artifactId>
            <version>${bestellung.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-adapter</artifactId>
            <version>${bestellung.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-adapter-out</artifactId>
            <version>${bestellung.version}</version>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-adapter-in</artifactId>
            <version>${bestellung.version}</version>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-domain</artifactId>
            <version>${bestellung.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-domain-service</artifactId>
            <version>${bestellung.version}</version>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-domain-model</artifactId>
            <version>${bestellung.version}</version>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-usecase</artifactId>
            <version>${bestellung.version}</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-usecase-out</artifactId>
            <version>${bestellung.version}</version>
        </dependency>
        <dependency>
            <groupId>de.envite.greenbpm.schulung.referenzimplementierung</groupId>
            <artifactId>aufgabenliste-usecase-in</artifactId>
            <version>${bestellung.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>