name: Frontend React - Continuous Integration

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/react/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/react/**'
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: ./frontend/react/package-lock.json
          cache: 'npm'

      - name: Install Dependencies
        working-directory: ./frontend/react
        run: npm ci

      - name: Run Lint
        working-directory: ./frontend/react
        run: npm run lint

      - name: Run Prettier Check
        working-directory: ./frontend/react
        run: npm run prettier:check

      - name: Run Tests
        working-directory: ./frontend/react
        run: npm test
